# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/cookbook/tests" # point this towards a Cargo.toml directory
    schedule:
      # Check for updates to Rust dependencies every week
      interval: "weekly"